//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "community")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uuid: Uuid,
    pub tech_id: i32,
    #[sea_orm(column_type = "Double")]
    pub ctc_range: f64,
    pub title: String,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::community_user::Entity")]
    CommunityUser,
}

impl Related<super::community_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommunityUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
