//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod community;
pub mod community_user;
pub mod leagues;
pub mod review;
pub mod review_slot;
pub mod technology;
pub mod user;
pub mod user_technology;
