//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub mod prelude;

pub mod leagues;
pub mod order;
pub mod order_signature;
pub mod otp;
pub mod review;
pub mod review_slot;
pub mod roadmap;
pub mod roadmap_user;
pub mod technology;
pub mod user;
pub mod user_technology;
