//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::technology::Entity as Technology;
pub use super::user::Entity as User;
pub use super::user_technology::Entity as UserTechnology;
