//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "technology")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub uuid: Uuid,
    pub title: String,
    #[sea_orm(unique)]
    pub normalized_title: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_technology::Entity")]
    UserTechnology,
}

impl Related<super::user_technology::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserTechnology.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
